# Generated by Django 5.0.6 on 2026-06-16 13:38

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=200)),
                ('problem_number', models.IntegerField()),
                ('subject_area', models.CharField(max_length=100)),
                ('concepts', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('estimated_difficulty', models.CharField(max_length=10)),
                ('frequency', models.CharField(blank=True, default='', max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_analyses', to='accounts.studygroup')),
            ],
            options={
                'ordering': ['priority', 'problem_number'],
            },
        ),
    ]
