# Generated by Django 5.0.6 on 2026-06-16 11:00

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('concepts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('problem_number', models.IntegerField()),
                ('subject_area', models.CharField(max_length=100)),
                ('solution_summary', models.TextField(blank=True, default='')),
                ('concepts', models.ManyToManyField(blank=True, related_name='problems', to='concepts.concept')),
            ],
            options={
                'ordering': ['problem_number'],
            },
        ),
        migrations.CreateModel(
            name='ProblemParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_correct', models.BooleanField(default=False)),
                ('understanding', models.CharField(choices=[('모름', '모름'), ('애매', '애매'), ('이해', '이해')], max_length=4)),
                ('concepts_covered', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('concepts_missed', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('errors', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('review_required', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='study.problem')),
            ],
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('session_date', models.DateField()),
                ('book', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.studygroup')),
            ],
            options={
                'ordering': ['-session_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='study.studysession'),
        ),
    ]
