# Generated by Django 5.0.6 on 2026-06-16 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='problemparticipant',
            constraint=models.UniqueConstraint(fields=('problem', 'name'), name='uniq_participant_per_problem'),
        ),
    ]
