# Generated by Django 5.0.6 on 2026-06-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_problemparticipant_uniq_participant_per_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='dedup_key',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
