# Generated by Django 5.0.6 on 2026-06-17 08:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_backfill_dedup_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='speakers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
